readme file was written
QQBratka/Cinema-app pull request #5
Opened 2022-01-19 16:52 UTC by QQBratka

2022-01-20 12:48 UTC, issugy requested changes
-` This is a web application that show simulation...` --> `This is a web application that show a simulation...`
 - `REST naming convention` --> `RESTfull application`
 - tell smth about what users can do with ur application
 
 common mistakes in student's projects, ckeck ur, please:
 - WbConfig class: line 10, set basePackages = {"cinema.controller"}
 - MovieSession class: add names for columns
 - Order class: add join column annotation and name for column order_time
 - Role class: rename field roleName to name
 - RoleEnum class: rename to RoleName
 - RoleName class: move in the Role class
 - ShoppingCart class: add join table annotation
 - Ticket class: add name for column

2022-01-24 05:40 UTC, Nick97-git reviewed
README:
-  a simulation of a cinema user service (remove user)
- Implementation details in project (in -> of)
- Spring (Web, REST, Security) -> (Core, Web, Security)
- remove JPQL from technologies
- Depending on the role you can use different endpoints:
- fix the display of this part
<img width="1004" alt="Screenshot 2022-01-24 at 07 29 11" src="https://user-images.githubusercontent.com/60258373/150727152-80aaec20-3d8a-48fc-bdd2-8a7e5455a9d5.png">
Also, remove words Both and Opportunities, it will be enough to write like this USER/ADMIN:
- fix this too
<img width="541" alt="Screenshot 2022-01-24 at 07 37 01" src="https://user-images.githubusercontent.com/60258373/150727803-9bab9956-9c8d-4b76-be4e-e01150ed7d5a.png">
- add /register endpoint to list of available endpoints
- Recommendations to run project: -> How to run the project:
- paraphrase the first three steps, so they sound like actions, also, add 6th step like launch the project
- paraphrase paragraph about created users and their passwords to make it more simple

2022-02-14 15:59 UTC, issugy requested changes
common mistakes in student's projects, check ur, please:
  
 - AppConfig class: setPackagesToScan("cinema.model")
 - WbConfig class: set basePackages = {"cinema.controller"}
 - MovieSession class: add names for columns
 - Order class: add join column annotation and name for column order_time
 - Role class: rename field roleName to name
 - RoleEnum class: rename to RoleName
 - RoleName class: move in the Role class
 - ShoppingCart class: add join table annotation
 - Ticket class: add name for column

2022-02-14 15:59 UTC, issugy commented on .gitignore
>  target/*
empty line )

2022-02-15 10:14 UTC, KseniiaMakarova requested changes

2022-02-15 10:14 UTC, KseniiaMakarova commented on src/main/java/cinema/config/AppConfig.java
> +@ComponentScan(basePackages = {"cinema.model"})
тут должен быть указан пакет со всеми бинами, а сейчас тут пакет model
соответственно, spring не сможет создать бины
ты запускал приложение?

исправить на cinema.model предлагалось ниже в этом классе, где ты конфигурируешь ORM

2022-02-15 10:14 UTC, KseniiaMakarova commented on src/main/java/cinema/model/MovieSession.java
> +    @JoinColumn(name = "show_time")
```suggestion
    @Column(name = "show_time")
```

2022-02-15 10:14 UTC, KseniiaMakarova commented on src/main/java/cinema/model/Order.java
> +    @JoinColumn(name = "order_time")
```suggestion
    @Column(name = "order_time")
```

2022-02-15 10:14 UTC, KseniiaMakarova commented on src/main/java/cinema/model/ShoppingCart.java
> +            joinColumns = @JoinColumn(name = "shopping_kart_id"),
```suggestion
    @JoinTable(name = "shopping_carts_tickets",
            joinColumns = @JoinColumn(name = "shopping_cart_id"),

```

2022-02-15 10:31 UTC, KseniiaMakarova approved these changes

2022-02-15 10:36 UTC, merged